### ISSUE TITLE
Exception occurs when loading library in a standalone WPF application

### ISSUE THREAD

**Issue by Horiztar** [luuksommers/SevenZipSharp.Interop#16]
Everything works fine in the development process when the SevenZipSharp.dll is not packed. But after I packed the whole application into an executable program, this exception occurred.
![image](https://user-images.githubusercontent.com/42955837/114442879-a01aaa80-9bff-11eb-880b-050c840e4743.png)
This is the code.
```
var libraryPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "7z.dll");
SevenZip.SevenZipBase.SetLibraryPath(libraryPath);
SevenZip.SevenZipExtractor extractor = new SevenZipExtractor(stream);
```

**Comment by quicoli** [comment]
Hi, your Library path isn't correct. You should set the Library path as 

`
// Toggle between the x86 and x64 bit dll
var path = Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location),Environment.Is64BitProcess ? "x64" : "x86", "7z.dll");
SevenZip.SevenZipBase.SetLibraryPath(path);
`

**Comment by Horiztar** [comment]
Thanks for your solution! Actually I have put the dlls in the "BaseDirectory". The problem is probably I compiled x86 executable program but using x64 dll.
