### ISSUE TITLE
Pointer value cannot be null exception

### ISSUE THREAD

**Issue by maxpl17** [luuksommers/SevenZipSharp.Interop#6]
Using 7z.dll version 18.5.0.0.

	Exception: Wartość nie może być zerowa. (eng: **Vallue cannot be null**)
Nazwa parametru: ptr  (Name of parameter: ptr)
	StackTrace:    in System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   in SevenZip.SevenZipLibraryManager.OutArchive(OutArchiveFormat format, Object user)
   in SevenZip.SevenZipCompressor.SetCompressionProperties()
   in SevenZip.SevenZipCompressor.GetArchiveUpdateCallback(Stream inStream, String password)
   in SevenZip.SevenZipCompressor.CompressStream(Stream inStream, Stream outStream, String password)

It gets randomly, catched in in 1/100 times of packing same input data.
I am using multithreading on independent source and output streams:

                        using (var compressedStream = new MemoryStream())
                        {
                            SevenZipBase.SetLibraryPath(@"7z.dll");
                            SevenZipCompressor compressor = new SevenZipCompressor { CompressionLevel = SevenZip.CompressionLevel.Fast };
                            compressor.CompressStream(inputStream, compressedStream);
                            return compressedStream.ToArray();
                        }

**Comment by luuksommers** [comment]
can you check if this also happens with newer versions of 7z.dll? e.g. version 19.00?

**Comment by luuksommers** [comment]
I've updated the package to 19.00, please also check https://github.com/tomap/SevenZipSharp ([Nuget](https://www.nuget.org/packages/SevenZipSharp.Net45)) for the new fork as the original SevenZipSharp has been deprecated (https://www.nuget.org/packages/SevenZipSharp).
