### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Samureimer** [luuksommers/SevenZipSharp.Interop#7]
Hi Luuk.
Your project seems to be missing a license and therefore your project is under exclusive copyright.
Because of this no one can legally copy, modify or distribute your work.

We would very much like to use your work and I would suggest that you put the project under the same license as 7z.

I would also suggest to mention 7z and link to their license for good measure.
https://www.7-zip.org/license.txt

Best regards, Mark.

**Comment by luuksommers** [comment]
My code is now available under MIT License, 7-zip license is also included! 👍

**Comment by Samureimer** [comment]
Thank you Luuk! :)
