### ISSUE TITLE
Exception: Element with same key already exists 

### ISSUE THREAD

**Issue by maxpl17** [luuksommers/SevenZipSharp.Interop#8]
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at SevenZip.SevenZipLibraryManager.InitUserOutFormat(Object user, OutArchiveFormat format)
   at SevenZip.SevenZipLibraryManager.LoadLibrary(Object user, Enum format)
   at SevenZip.SevenZipCompressor.CompressStream(Stream inStream, Stream outStream, String password)
  
Using in multi threads at same time:
                        using (var compressedStream = new MemoryStream())
                        {
                            SevenZipCompressor compressor = new SevenZipCompressor { CompressionLevel = SevenZip.CompressionLevel.Fast };
                            **compressor.CompressStream(memoryStream, compressedStream);** //Exception in this line
                            return compressedStream.GetBuffer();
                        }

Also in same time was shown: Managed Debugging Assistant 'RaceOnRCWCleanup' An attempt has been made to free an RCW that is in use. The RCW is in use on the active thread or another thread. Attempting to free an in-use RCW can cause corruption or data loss.

Looks like problem of multi-threaded access? Maybe use ConcurrentDictionary?

**Comment by luuksommers** [comment]
This is not an issue with the Interop, it's probably an issue with SevenZipSharp. I would recommend posting this issue there.

**Comment by luuksommers** [comment]
This is a bug in SevenZipSharp itself, please check https://github.com/tomap/SevenZipSharp ([Nuget](https://www.nuget.org/packages/SevenZipSharp.Net45)) for the new fork as the original SevenZipSharp has been deprecated (https://www.nuget.org/packages/SevenZipSharp).
